customizations = {
    "styles": [
        {"styleName": "Crew Neck"},
        {"styleName": "V-Neck"},
        {"styleName": "Long Sleeve"},
        {"styleName": "Tank Top"}
    ],

    "genders": [
        {"genderName": "Male"},
        {"genderName": "Female"},
        {"genderName": "Unisex"}
    ],

    "colors": [
        {"colorName": "White"},
        {"colorName": "Black"},
        {"colorName": "Blue"},
        {"colorName": "Red"},
        {"colorName": "Green"},
        {"colorName": "Custom colors"}
    ],

    "sizes": [
        {"sizeName": "XS"},
        {"sizeName": "S"},
        {"sizeName": "M"},
        {"sizeName": "L"},
        {"sizeName": "XL"},
        {"sizeName": "XXL"}
    ],

    "printing_options": [
        {"optionName": "Screen Printing"},
        {"optionName": "Embroidery"},
        {"optionName": "Heat Transfer"},
        {"optionName": "Direct-to-Garment"}
    ]
}


faqs = [{
      "id": 1,
      "question": "What sizes are available?",
      "answer": "We offer sizes ranging from XS to XXL, including a size chart to help you choose the best fit. Kids' sizes from 2T to XL are also available."},
    { "id": 2,
      "question": "Can I add my own design to the t-shirt?",
      "answer": "Yes, you can upload your design or choose from our library of designs."},
    { "id": 3,
      "question": "What materials are the t-shirts made from?",
      "answer": "Our t-shirts are available in 100% cotton, cotton-polyester blend, and organic cotton."},
    { "id": 4,
      "question": "What is the delivery time for a custom t-shirt?",
      "answer": "Delivery typically takes 1-2 weeks depending on your location."},
    { "id": 5,
      "question": "How can I track my order?",
      "answer": "You can track your order by logging into your account and viewing your order history."},
    { "id": 6,
      "question": "Is there a minimum order quantity for custom t-shirts?",
      "answer": "No, you can order as few as one custom t-shirt."},
    { "id": 7,
      "question": "What printing options do you offer?",
      "answer": "We offer screen printing, embroidery, heat transfer, and direct-to-garment printing."},
    { "id": 8,
      "question": "Can I see a preview of my design before placing an order?",
      "answer": "Yes, our design tool provides a preview of your t-shirt before you finalize your order."},
    { "id": 9,
      "question": "Do you offer bulk discounts?",
      "answer": "Yes, we offer discounts for bulk orders. Please contact our sales team for more information."},
    { "id": 10,
      "question": "What is your return policy for custom t-shirts?",
      "answer": "Custom t-shirts can be returned within 30 days of delivery, provided they are in their original condition."},
    { "id": 11,
      "question": "Can I change my order after it has been placed?",
      "answer": "Changes can be made within 24 hours of placing the order. Please contact customer support for assistance."},
    { "id": 12,
      "question": "What payment methods do you accept?",
      "answer": "We accept major credit cards, PayPal, and Apple Pay."},
    { "id": 13,
      "question": "How do I care for my custom t-shirt?",
      "answer": "We recommend washing your t-shirt inside out in cold water and tumble drying on low to preserve the print."},
    { "id": 14,
      "question": "Can I order matching t-shirts for an event?",
      "answer": "Yes, you can design and order matching t-shirts for events, teams, and groups."},
    { "id": 15,
      "question": "Do you offer kids’ sizes?",
      "answer": "Yes, we offer a range of kids’ sizes from 2T to XL."},
    { "id": 16,
      "question": "Are your materials eco-friendly?",
      "answer": "We offer eco-friendly options like organic cotton and recycled polyester."},
    { "id": 17,
      "question": "Can I get assistance with my design?",
      "answer": "Yes, our design team is available to help you create the perfect t-shirt."},
    { "id": 18,
      "question": "What happens if my order is damaged upon arrival?",
      "answer": "If your order arrives damaged, please contact us with a photo of the damage, and we will send a replacement."},
    { "id": 19,
      "question": "Do you ship internationally?",
      "answer": "Yes, we ship to most countries worldwide. Shipping times and rates may vary."},
    { "id": 20,
      "question": "How can I contact customer support?",
      "answer": "You can reach customer support via email, phone, or live chat on our website."},
    { "id": 21,
      "question": "Can I reorder a previous design?",
      "answer": "Yes, you can easily reorder previous designs by logging into your account and selecting from your order history."},
    { "id": 22,
      "question": "Do you offer gift cards?",
      "answer": "Yes, we offer gift cards that can be purchased and used towards any custom t-shirt order."},
    { "id": 23,
      "question": "Are there any special care instructions for eco-friendly materials?",
      "answer": "For eco-friendly materials like organic cotton, we recommend washing in cold water and hanging to dry to maintain the fabric’s integrity."},
    { "id": 24,
      "question": "What is TeeCustomizer?",
      "answer": "TeeCustomizer is an online platform that allows users to design and order custom t-shirts. We cater to both individual customers and businesses, providing a range of printing options and high-quality materials."},
    { "id": 25,
      "question": "How long has TeeCustomizer been in business?",
      "answer": "TeeCustomizer has been proudly serving customers since 2017."},
    { "id": 26,
      "question": "Where is TeeCustomizer located?",
      "answer": "Our headquarters is located in Riga, Latvia, and we operate multiple production facilities to ensure efficient service and delivery."},
    { "id": 27,
      "question": "Can I cancel my order?",
      "answer": "Orders can be canceled within 24 hours of placing the order. Please contact customer support for assistance."
    },
    { "id": 28,
      "question": "What are your business hours?",
      "answer": "Our customer support team is available Monday to Friday, 9 AM to 6 PM (local time)."},
    { "id": 29,
      "question": "Are there any additional charges for international shipping?",
      "answer": "Yes, additional shipping charges and customs fees may apply for international orders."},
    { "id": 30,
      "question": "Do you offer expedited shipping options?",
      "answer": "Yes, expedited shipping options are available at an additional cost. Please select the expedited shipping option at checkout."},
    { "id": 31,
      "question": "Can I use multiple discount codes on a single order?",
      "answer": "No, only one discount code can be applied per order."},
    { "id": 32,
      "question": "Do you offer design templates?",
      "answer": "Yes, we offer a variety of design templates to help you get started."}
]


keywords = ["business", "design","hour","custom",
            "customer", "instruction", "policy",
            "option", "event", "gift", "material",
            "shirt", "arrival", "delivery", "quantity", 
            "customization", "colour", "colours", "gender", 
            "printing", "printing options"]